# set-window-option -g mode-mouse on
setw -g mode-keys vi

bind-key -n C-S-Up resize-pane -U 5
bind-key -n C-S-Down resize-pane -D 5
bind-key -n C-S-Left resize-pane -L 10
bind-key -n C-S-Right resize-pane -R 10

set -g default-terminal "screen-256color"
set-option -g default-shell "/usr/bin/fish"
set-option -g renumber-windows on
set -g status-bg colour8
set -g status-fg white
set-window-option -g window-status-current-fg colour11
set -g pane-active-border-fg colour11
set -g pane-border-fg colour8

set-window-option -g aggressive-resize

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Open new split panes with the same pwd and the current pane
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# prevent tmux renaming windows
set -g automatic-rename off
set -g allow-rename off
