theme = "base16_transparent"

[editor]
auto-format = true
auto-save = true
bufferline = "always"
color-modes = true
cursorline = true
insert-final-newline = true
text-width = 150
true-color = true
line-number = "relative"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "version-control"]
center = ["file-modification-indicator", "file-name"]
right = ["workspace-diagnostics", "diagnostics", "register", "selections", "position", "file-encoding", "file-type"]

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
