theme = "tokyonight"

[editor]
bufferline = "never"
color-modes = true
completion-replace = true
cursorline = true
end-of-line-diagnostics = "hint"
insert-final-newline = true
line-number = "relative"
popup-border = "all"
text-width = 160
true-color = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "read-only-indicator"]
center = ["file-type", "file-modification-indicator", "file-name"]
right = ["diagnostics", "register", "selections", "position"]

[editor.statusline.mode]
normal = "NOR"
insert = "INS"
select = "SEL"

[editor.lsp]
display-messages = true
display-progress-messages = true
display-inlay-hints = false

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
render = true
skip-levels = 2

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
"C-l" = [
  ":write-all",
  ":insert-output lazygit >/dev/tty",
  ":redraw",
  ":reload-all",
]

C-g = [
  ":write-all",
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
  ":reload-all",
]

# [keys.normal.space.g]
# a = ":sh git add '%{buffer_name}'"

[keys.normal.space.g]
f = "changed_file_picker"
a = ":sh git add '%{buffer_name}'"
r = ":reset-diff-change"
# inline blame
b = ":run-shell-command ~/.config/helix/utils/blame_line_pretty.sh %{buffer_name} %{cursor_line}"
# full file changes of last commit under cursor
B = ':open %sh{~/.config/helix/utils/blame_file_pretty.sh %{buffer_name} %{cursor_line}}'
# inline hunk changes
h = ':run-shell-command ~/.config/helix/utils/git-hunk.sh %{buffer_name} %{cursor_line} 3'
