theme = "material_palenight"

[editor]
auto-save = true
bufferline = "never"
color-modes = true
completion-replace = true
cursorline = true
insert-final-newline = true
text-width = 160
true-color = true
line-number = "relative"

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-type", "file-modification-indicator", "file-name", "read-only-indicator"]
right = ["workspace-diagnostics", "diagnostics", "register", "selections", "position", "file-encoding"]

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
