theme = "default"

[editor]
bufferline = "never"
color-modes = true
completion-replace = true
cursorline = true
end-of-line-diagnostics = "hint"
insert-final-newline = true
line-number = "relative"
rulers = [100]
popup-border = "all"
text-width = 160
true-color = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "read-only-indicator"]
center = ["file-type", "file-modification-indicator", "file-name"]
right = ["diagnostics", "register", "selections", "position"]

[editor.statusline.mode]
normal = "NOR"
insert = "INS"
select = "SEL"

[editor.lsp]
display-messages = true
display-progress-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
render = true
skip-levels = 2

[editor.soft-wrap]
enable = false
wrap-at-text-width = true

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
"C-l" = [
    ":write-all",
    ":insert-output lazygit >/dev/tty",
    ":redraw",
    ":reload-all"
]
