[language-server.gpt]
command = "bun"
args = ["run", "/Users/nate/bin/helix-gpt", "--handler", "copilot"]
# with logging
# args = ["run", "/Users/nate/bin/helix-gpt", "--handler", "copilot", "--logFile", "/tmp/helix-gpt.log"]

[language-server.ruby-lsp]
command = "ruby-lsp"

[[language]]
name = "ruby"
auto-format = true
formatter = { command = "rubocop", args = ["--stdin", "foo.rb", "-a", "--stderr", "--fail-level", "fatal"] }
language-servers = ["ruby-lsp"]

[[language]]
name = "typescript"
auto-format = false
formatter = { command = "prettier", args = ["--parser", "typescript"] }
language-servers = [
    "typescript-language-server"
]

[[language]]
name = "go"
language-servers = [
    "gopls",
    "gpt"
]

[[language]]
name = "kotlin"
indent = { tab-width = 2, unit = "  " }
formatter = { command = "ktfmt" , args = [] }
