[language-server.gpt]
command = "bun"
args = ["run", "/Users/nate/bin/helix-gpt", "--handler", "copilot"]
# with logging
# args = ["run", "/Users/nate/bin/helix-gpt", "--handler", "copilot", "--logFile", "/tmp/helix-gpt.log"]

[language-server.ruby-lsp]
command = "ruby-lsp"

[language-server.toml]
command = "taplo"
args = ["lsp", "stdio"]

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://json.schemastore.org/taskfile.json" = "{Taskfile,tasks}.yml"

[[language]]
name = "ruby"
auto-format = true
formatter = { command = "rubocop", args = ["--stdin", "foo.rb", "-a", "--stderr", "--fail-level", "fatal"] }
language-servers = ["ruby-lsp"]

[[language]]
name = "toml"
auto-format = true
language-servers = ["toml"]

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }
language-servers = [
    "typescript-language-server"
]

[[language]]
name = "javascript"
file-types = ["js", "jsx", "mjs", "cjs", "page"]
auto-format = true
formatter = { command = "prettier", args = ["--write", "--parser", "typescript"] }
language-servers = [
    "typescript-language-server"
]

[[language]]
name = "go"
language-servers = [
    "gopls",
]

[[language]]
name = "kotlin"
indent = { tab-width = 2, unit = "  " }
formatter = { command = "ktfmt" , args = [] }
