tap "homebrew/bundle"
tap "notnmeyer/daylog-cli"
tap "notnmeyer/tsk"

brew "gh"
brew "notnmeyer/daylog-cli/daylog"
brew "notnmeyer/tsk/tsk"

cask "1password-cli"
cask "ngrok"
cask "orbstack"
cask "wezterm"
